# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: 
    displayName: Build Job
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'service-connection-ACR'
        repository: 'manual-aksdevopsacr-svc'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(Build.SourceVersion
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        OverWrite: true
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo After copying to Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory) ;
          pwd
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'kube-manifests'
        publishLocation: 'Container'
  
  
