# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self
stages:
- stage: stage1
  displayName: Kubectl in BASH
  jobs:
  - job: job1
    displayName: displayname1
    pool: Default
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          ls
          kubectl get pods
          kubectl apply -f ./kube-manifests