# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
- repo: self
stages:
- stage: stage1
  displayName: Kubectl in BASH
  jobs:
  
  - job: Build_and_push
    displayName: displayname1
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'ACRTestGil'
        repository: 'app1/gil-nginx'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'v2'
      #  tags: '$(Build.BuildId)' 

  - job: Deploy_on_aks
    displayName: displayname1
    pool: Default
    steps:
    - task: Bash@3
      displayName: Deploy on aks
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          ls
          kubectl get pods
          kubectl apply -f ./kube-manifests
    